image: python:2.7

before_script:
  - pip install -r testing_requirements.txt

validation:
  script:
    - find . -name "*.py" -exec pep8 {} \;
    - find . -name "*.py" -exec pep257 {} \;
    - radon mi hooker
    - radon cc hooker